### ISSUE TITLE
User Story #7

### ISSUE THREAD

**Issue by Mingyang-Sun** [cse110-sp24-group10/warmup-exercise#12]
## User Story
As a User, I want to know when I have submitted my sentiment/feedback

## Jira Link
https://team10-cse110.atlassian.net/jira/software/projects/TEAM10/boards/2?selectedIssue=TEAM10-7

## Acceptance Criteria
For this story, we want to make sure to enlarge or highlight the icon as a user hovers over it, and when a user actually clicks an icon, we want to have text pop up which says “Thank you for your response!“

## Tasks
- [ ] Task 1: Enlarge the icon as a user hovers over it
- [ ] Task 2: With text pop up which says “Thank you for your response!“ when a user clicks it

## Priority
- [ ] High/Medium/Low
