### ISSUE TITLE
STORY 4

### ISSUE THREAD

**Issue by anishcd** [cse110-sp24-group10/warmup-exercise#17]
## User Story
**As a** user,  
**I want** to be able to share further feedback in text.

## Jira Link
[View this user story in Jira](https://team10-cse110.atlassian.net/browse/TEAM10-4?atlOrigin=eyJpIjoiZTIxOTMzM2YyMjU2NDQzNDk0YmEzZTgyYmQwMWY1ZDAiLCJwIjoiaiJ9)

## Acceptance Criteria
- [x] Criterion 1: Have a text box appear when a user clicks an icon indicating a submission of a sentiment
- [x] Criterion 2: Along with a submit button
- [x] Criterion 3: Once a user submits a text response, the page should show some confirmation that this has been sent.

## Tasks
- [x] Task 1: The text box exists, but is linked to the wrong element so we need to fix this (look at related issues).
- [x] Task 2: Add a submit button and some sort of feedback when the button is clicked, reset the form.
- [x] Task 3: Make sure design choices are met.

## Related Issues

#15 #16

**Comment by anishcd** [comment]
Resolved
