### ISSUE TITLE
STORY 1

### ISSUE THREAD

**Issue by anishcd** [cse110-sp24-group10/warmup-exercise#18]
## User Story
**As a** mouse-less user,  
**I want** to be able to navigate the form with my keyboard.

## Jira Link
[View this user story in Jira](https://team10-cse110.atlassian.net/browse/TEAM10-1?atlOrigin=eyJpIjoiNmQxYWRjYWE2MDczNDhjNzkzMGVlNDYzMGMwNjhlNzgiLCJwIjoiaiJ9)

## Acceptance Criteria
- [x] Criterion 1: The left and right arrow keys should be able to switch between icons.
- [x] Criterion 2: The enter/return key should submit a sentiment as if it has been clicked.

## Tasks
- [x] Task 1: This may be able to be done in pure HTML, or otherwise JS
