### ISSUE TITLE
STORY 3

### ISSUE THREAD

**Issue by anishcd** [cse110-sp24-group10/warmup-exercise#19]
## User Story
**As a** accessibility-prioritizing user,  
**I want** to have customizable accessibility options.

## Jira Link
[View this user story in Jira](https://team10-cse110.atlassian.net/browse/TEAM10-3?atlOrigin=eyJpIjoiMTk2NGEwOTFmNTFjNDY3ZGFiZTc1ZmU4NzE3OWRhYTYiLCJwIjoiaiJ9)

## Acceptance Criteria
- [x] Criterion 1: Toggle in the top-right corner of the page which allows the user to switch between a light and dark mode
- [x] Criterion 2: The default should be in light mode

## Tasks
- [x] Task 1: Look into changing the CSS values, following the design we have constructed
- [x] Task 2: If time allows, look into adding some text or icon to indicate what the current mode is set to.

**Comment by mic051** [comment]
Finished all task and criterion locally. Waiting to pull changes, merge, and push to main.
