### ISSUE TITLE
STORY 2

### ISSUE THREAD

**Issue by anishcd** [cse110-sp24-group10/warmup-exercise#20]
## User Story
**As a** mobile user,,  
**I want** to have the page work on different screen sizes.

## Jira Link
[View this user story in Jira](https://team10-cse110.atlassian.net/browse/TEAM10-2?atlOrigin=eyJpIjoiYmI1MmRiN2M4YTEyNDM0MWJmMTFhMmJkMzk0NTZkODkiLCJwIjoiaiJ9)

## Acceptance Criteria
- [ ] Criterion 1: The sentiment widget, along with the feedback box should scale in size with different screen sizes

## Tasks
- [ ] Task 1: Look into the CSS properties of the element and all the divs within it
- [ ] Task 2: Validate in the console with different screen sizes that scaling does not mess up the widget
